spring:
  #database
  data:
    mongodb:
      uri: ${MONGO_DATABASE_URI:mongodb://localhost:27017}
      database: post-ai-database
      auto-index-creation: true

  rabbitmq:
    addresses: ${MS_ADDRESS}
    queues:
      send-order-queue: order
      order-processed-queue: order-process-result

  servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB

#AWS
s3:
  bucket-order: ${BUCKETORDERNAME}
  bucket-template: ${BUCKETTEMPLATENAME}
  region: us-east-2

aws:
    access_key_id: ${ACCESSKEYID}
    secret_access_key: ${SECRETACCESSKEY}

thumbnail:
  width: ${SCALINGWIDTH:200}
  height: ${SCALINGHEIGHT:200}

# Server configuration
server:
  port: 8080