spring:
  #database
  data:
    mongodb:
      uri: ${MONGO_DATABASE_URI:mongodb://localhost:27017}
      database: post-ai-database
      auto-index-creation: true

  rabbitmq:
    addresses: ${MS_ADDRESS}
    queues:
      send-order-queue: order

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

#AWS
s3:
  bucket-order: ${BUCKETORDERNAME}
  bucket-template: ${BUCKETTEMPLATENAME}
  region: us-east-2

aws:
    access_key_id: ${ACCESSKEYID}
    secret_access_key: ${SECRETACCESSKEY}

# Server configuration
server:
  port: 8080